name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version  # 确保 pnpm 可用

      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Generate static files
        run: |
          hexo generate

      - name: CNAME file
        run: echo "blog.zmal.top" > ./CNAME
