name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
          submodules: true
                
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          
      - name: Install dependencies
        run: |
          npm install -g pnpm hexo-cli  # 全局安装 pnpm
          pnpm install             # 安装项目依赖
          pnpm install hexo-neat --save #项目压缩
          pnpm install --save hexo-tag-bilibili #b站视频        
          pnpm install hexo-autoprefixer --save #css兼容性

      # Step 4: 生成静态文件
      - name: Generate static files
        run: |
          hexo generate           # 等价于 hexo g

      # Step 5: 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # 使用 PAT 认证
          publish_dir: ./public                               # 指定生成的静态文件目录
